version: "3.8"

services:
  user-service:
    image: user_service:latest
    container_name: user-service
    env_file: .env
    depends_on:
      - user-db
      - redis
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=${USER_SERVICE_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${USER_SERVICE_USER}
      - SPRING_DATASOURCE_PASSWORD=${USER_SERVICE_PASSWORD}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SERVICE_SECRET=${SERVICE_SECRET}
      - SPRING_PROFILES_ACTIVE=docker
      - USER_SERVICE_PORT=8081
    networks:
      - internal

  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      - POSTGRES_DB=${USER_SERVICE_DB}
      - POSTGRES_USER=${USER_SERVICE_USER}
      - POSTGRES_PASSWORD=${USER_SERVICE_PASSWORD}
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - internal

  auth-service:
    image: auth_service:latest
    container_name: auth-service
    env_file: .env
    depends_on:
      - auth-db
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=${AUTH_SERVICE_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${AUTH_SERVICE_USER}
      - SPRING_DATASOURCE_PASSWORD=${AUTH_SERVICE_PASSWORD}
      - SERVICE_SECRET=${SERVICE_SECRET}
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH_SERVICE_PORT=8082
    networks:
      - internal

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      - POSTGRES_DB=${AUTH_SERVICE_DB}
      - POSTGRES_USER=${AUTH_SERVICE_USER}
      - POSTGRES_PASSWORD=${AUTH_SERVICE_PASSWORD}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - internal

  order-service:
    image: order-service:latest
    container_name: order-service
    env_file: .env
    depends_on:
      - order-db
      - kafka
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=${ORDER_SERVICE_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${ORDER_SERVICE_USER}
      - SPRING_DATASOURCE_PASSWORD=${ORDER_SERVICE_PASSWORD}
      - SERVICE_SECRET=${SERVICE_SECRET}
      - SPRING_PROFILES_ACTIVE=docker
      - ORDER_SERVICE_PORT=8083
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal

  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      - POSTGRES_DB=${ORDER_SERVICE_DB}
      - POSTGRES_USER=${ORDER_SERVICE_USER}
      - POSTGRES_PASSWORD=${ORDER_SERVICE_PASSWORD}
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - internal

  payment-service:
    image: payment-service:latest
    container_name: paymentService
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "8084:8084"
    environment:
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - MONGODB_URI=mongodb://mongodb:27017/payments
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EXTERNAL_API_URL=https://www.randomnumberapi.com/api/v1.0
      - SPRING_PROFILES_ACTIVE=docker
      - PAYMENT_SERVICE_PORT=8084
    networks:
      - internal

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - internal

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - internal

  redis:
    image: redis:7-alpine
    container_name: redis
    expose:
      - "6379"
    networks:
      - internal

  api-gateway:
    build: .
    image: api-gateway:latest
    container_name: api-gateway
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - auth-service
      - user-service
      - order-service
      - payment-service
    environment:
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - ORDER_SERVICE_URL=${ORDER_SERVICE_URL}
      - PAYMENT_SERVICE_URL=${PAYMENT_SERVICE_URL}
      - SERVICE_SECRET=${SERVICE_SECRET}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  user-db-data:
  auth-db-data:
  order-db-data:
  mongodb_data:
