server:
  port: 8080

spring:

  application:
    name: api-gateway

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000ms

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowed-headers:
              - "*"

      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://user-service:8081}
          predicates:
            - Path=/api/users/**,/api/cards/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 50
                key-resolver: "#{@ipKeyResolver}"

        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://auth-service:8082}
          predicates:
            - Path=/api/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://order-service:8083}
          predicates:
            - Path=/api/orders/**,/api/items/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 50
                key-resolver: "#{@ipKeyResolver}"

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://payment-service:8084}
          predicates:
            - Path=/api/payments/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 50
                key-resolver: "#{@ipKeyResolver}"

        - id: user-service-docs
          uri: ${USER_SERVICE_URL:http://user-service:8081}
          predicates:
            - Path=/v3/api-docs/user
          filters:
            - RewritePath=/v3/api-docs/user, /v3/api-docs

        - id: auth-service-docs
          uri: ${AUTH_SERVICE_URL:http://auth-service:8082}
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth, /v3/api-docs

        - id: order-service-docs
          uri: ${ORDER_SERVICE_URL:http://order-service:8083}
          predicates:
            - Path=/v3/api-docs/order
          filters:
            - RewritePath=/v3/api-docs/order, /v3/api-docs

        - id: payment-service-docs
          uri: ${PAYMENT_SERVICE_URL:http://payment-service:8084}
          predicates:
            - Path=/v3/api-docs/payment
          filters:
            - RewritePath=/v3/api-docs/payment, /v3/api-docs

security:
  jwt:
    secret: ${JWT_SECRET}

internal:
  internal-secret: ${INTERNAL_SECRET}

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /v3/api-docs/user
      - name: auth-service
        url: /v3/api-docs/auth
      - name: order-service
        url: /v3/api-docs/order
      - name: payment-service
        url: /v3/api-docs/payment
    path: /swagger-ui.html